-- AlterTable
ALTER TABLE "project_images" ADD COLUMN     "focal_x" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN     "focal_y" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN     "zoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
