version: '3.8'
name: rccf

services:
  web_rccf:
    container_name: website
    build:
      context: .
      dockerfile: ./dockerfile
      args:
        - DATABASE_URL=postgresql://postgres:password@postgres_rccf:5432/RCCF
        - SECRET_STRIPE_KEY=${SECRET_STRIPE_KEY}
        - PUBLIC_STRIPE_KEY=${PUBLIC_STRIPE_KEY}
        - POSTMARK_API_TOKEN=${POSTMARK_API_TOKEN}
        - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
        - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
        - DISCORD_MEMBER_ROLE_ID=${DISCORD_MEMBER_ROLE_ID}
        - DISCORD_PROJECT_LEAD_ROLE_ID=${DISCORD_PROJECT_LEAD_ROLE_ID}
        - DISCORD_TEAM_LEAD_ROLE_ID=${DISCORD_TEAM_LEAD_ROLE_ID}
    restart: unless-stopped
    depends_on:
      - postgres_rccf
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres_rccf:5432/RCCF
    ports:
      - 4173:4173
    networks:
      - services

  postgres_rccf:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA /data/postgres
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - services
  # pgadmin:
  #   restart: unless-stopped
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
  #   ports:
  #     - '${PGADMIN_PORT:-5050}:80'
  #   depends_on:
  #     - postgres
  #   networks:
  #     - services

volumes:
  data:
  pgadmin:


networks:
  services:
    name: services
    driver: bridge
