FROM node:18-alpine3.18
WORKDIR /RCCF-WEB
COPY . .
RUN npm i

ARG DATABASE_URL
ARG SECRET_STRIPE_KEY
ARG PUBLIC_STRIPE_KEY
ARG POSTMARK_API_TOKEN
ARG DISCORD_BOT_TOKEN
ARG DISCORD_GUILD_ID
ARG DISCORD_MEMBER_ROLE_ID
ARG DISCORD_PROJECT_LEAD_ROLE_ID
ARG DISCORD_TEAM_LEAD_ROLE_ID

ENV DATABASE_URL=$DATABASE_URL
ENV SECRET_STRIPE_KEY=$SECRET_STRIPE_KEY
ENV PUBLIC_STRIPE_KEY=$PUBLIC_STRIPE_KEY
ENV POSTMARK_API_TOKEN=$POSTMARK_API_TOKEN
ENV DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN
ENV DISCORD_GUILD_ID=$DISCORD_GUILD_ID
ENV DISCORD_MEMBER_ROLE_ID=$DISCORD_MEMBER_ROLE_ID
ENV DISCORD_PROJECT_LEAD_ROLE_ID=$DISCORD_PROJECT_LEAD_ROLE_ID
ENV DISCORD_TEAM_LEAD_ROLE_ID=$DISCORD_TEAM_LEAD_ROLE_ID

RUN npx prisma generate
RUN npm run build
EXPOSE 4173
# This is Temporary as we dont have a proper build system yet
ENTRYPOINT [ "npm","run","preview" ]