-- AlterTable
ALTER TABLE "users" ADD COLUMN     "photo_focal_x" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN     "photo_focal_y" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN     "photo_zoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
